# Generated by Django 5.2.1 on 2025-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('standard', 'Standard (3-5 Days)'), ('express', 'Express (1-2 Days)'), ('Cod', 'Cash on delivery (Today)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('mpesa', 'M-PESA'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Crypto')], max_length=20),
        ),
    ]
